name: Bash Pinger

on:
  push:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Pinger
        run: |
          bash pinger.sh
